### ISSUE TITLE
ok, i run it, what next?

### ISSUE THREAD

**Issue by texrg** [JackonYang/captcha-tensorflow#12]
What I can to do to solve my image?

I have image and need get string to resolve captcha, where is code?

Is possible to tell what is format of data to train and test? 
filename is only 'string'_some.png 
some will be everything?

**Comment by JackonYang** [comment]
the repo is only a demo for learning only.

There are several more steps to put this prototype on production.

Ping me for paid technical support if you want to simply run the code to solve your image.

**Comment by texrg** [comment]
;(
