### ISSUE TITLE
Why not the training accuracy and test accuracy rise?

### ISSUE THREAD

**Issue by LouZhiX** [JackonYang/captcha-tensorflow#14]
我是直接使用的此代码，其中只是更改了数据集的大小，设定的数据集为30000张训练集，6000张测试集，每幅验证码由数字和大小写字符构成。但是实际在训练时发现train accuracy 和test accuracy都上不去，而且loss达到4.12左右就不再下降，请问这是什么原因？
![2018-04-11 11-18-36](https://user-images.githubusercontent.com/24652283/38594697-2a3c68e4-3d7a-11e8-89ee-2d3d5a78ca34.png)

![2018-04-11 11-10-05](https://user-images.githubusercontent.com/24652283/38594585-76e0b854-3d79-11e8-9cb0-87af31227db0.png)

**Comment by OSchwark** [comment]
interesting, label_size=62 means you have A-Za-z0-9. I also tried that (with different captcha images than in example) and also have only ~2-3% accuracy. Removing all letters leads to good values.
