### ISSUE TITLE
how should i adpat to a different image size?

### ISSUE THREAD

**Issue by xja** [JackonYang/captcha-tensorflow#22]
there are some errors indicates me that image size doesn't fit

`Invalid argument: Input to reshape is a tensor with 832000 values, but the requested shape requires a multiple of 40000`

original size generated from captcha was 100*100, could you please tell me how to adpat to a new size, for example, my image size is 200*50

**Comment by daniilsavchuk** [comment]
So the architecture here using 2 max pulling in different layers. So your input dimensions over W and H should be divisible by 4
