### ISSUE TITLE
train datesets accuracy is very low,why?

### ISSUE THREAD

**Issue by YouSmart2016** [JackonYang/captcha-tensorflow#25]
train count: 14817, valid count: 6351, test count: 9072

![image](https://user-images.githubusercontent.com/17959627/90479251-f0b93100-e160-11ea-845c-783793561952.png)

![image](https://user-images.githubusercontent.com/17959627/90479267-f747a880-e160-11ea-977f-df9122ca6bf8.png)

how to deal with it??

**Comment by JackonYang** [comment]
the model is not working. 0.1 accuracy is the same prob as a random prediction.

check your TensorFlow version and follow the README step by step exactly.
