### ISSUE TITLE
TypeError: run() takes no arguments (2 given)

### ISSUE THREAD

**Issue by webcssphp** [JackonYang/captcha-tensorflow#7]
$ python simple_softmax.py images/char-1-epoch-2000/

Traceback (most recent call last):
  File "simple_softmax.py", line 70, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
TypeError: run() takes no arguments (2 given)

**Comment by JackonYang** [comment]
看起来是 tensorflow 版本不匹配。

我的版本是 1.0.0

**Comment by webcssphp** [comment]
确是版本问题，解决了，感谢
