### ISSUE TITLE
验证码不用灰度化降噪去干扰线之类的处理么，我的电脑训练四个字符的时候卡死了好奇怪

### ISSUE THREAD

**Issue by jiaoyiyuan** [JackonYang/captcha-tensorflow#8]
验证码不用灰度化降噪去干扰线之类的处理么，我的电脑训练四个字符的时候卡死了好奇怪

**Comment by JackonYang** [comment]
1. 灰度化降噪去干扰线, 这是传统算法。
2. 四个字符跟单字符，计算量在同一个数量级。只要单字符的不卡，四个字符也不应该卡。
