### ISSUE TITLE
is possible resolve this?

### ISSUE THREAD

**Issue by letarg0** [JackonYang/captcha-tensorflow#9]
https://github.com/aero2a/kape-

I can found php library. Is possible next using C code to resolve after training net?

**Comment by JackonYang** [comment]
I can not read the language in that repo.

I checked the pictures, it is possible to resolve those pictures.

**Comment by letarg0** [comment]
How i can create learn and test data?
Is possible to using config file? not filename as inut data?

**Comment by JackonYang** [comment]
> How i can create learn and test data?

refer to: https://github.com/JackonYang/captcha-tensorflow#generate-dataset-for-training

> Is possible to using config file? not filename as inut data?

you need to change the code to support it.

**Comment by letarg0** [comment]
can I generate image 
a_0001.png with 'a' char image
a_0002....etc?
this hex codes are not important?

is possible using other size of data for example 1000 ?

`$python datasets/gen_captcha.py -d --npi 1 -n 1000`

**Comment by texrg** [comment]
forget, this is not a solution

**Comment by JackonYang** [comment]
@letarg0 https://github.com/JackonYang/captcha-tensorflow#1-char-captcha

**Comment by letarg0** [comment]
i create https://github.com/letarg0/obrazy
trouble is with line on image and meybe bend chars?
on https://github.com/letarg0/obrazy/tree/master/letter_images are separate chars
